src/helpers.cc
Fix a build failure with musl due missing open/O_RDWR/O_CREAT/O_APPEND.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> helpers.cc: add missing includes

CMakeLists.txt, src/CMakeLists.txt, src/composeappmanager.cc, src/helpers.cc, src/helpers.h, src/main.cc, src/ostree.cc, tests/CMakeLists.txt, tests/helpers_test.cc
1) It turned out that there are two instances of ReportQueue running in the
context of aktualizr-lite. One instance is owned by LiteClient the
second one by SotaUptaneClient. Each instance runs a thread that fetches
events from the DB and sends them to the backend, this procedure is not
synchronized what causes the race condition with side effects like
sending the same event twice.
The key question here is why do we need both clients LiteClient and SotaUptaneClient?
Taking into account that SotaUptaneClient is tuned for the Uptane
use-case it doesn't make sense to use it as it requires hacking around in order
to eliminate the Uptane specific logic that is not required in the TUF
case as well as the logic around Secondary support. Instead we can just
reuse the libaktualizr's mechanisms in …
=> Fix a race condition in the event reporting

scripts/clang-tidy-wrapper.sh, src/composeappmanager.cc, src/composeappmanager.h
- switch to 2020.7+fio
- adjust aktualizr-lite to aktualizr 2020.7
- changes in PackageManagerInterface::fetchTarget signature
- added symlink to clang-tidy-wrapper.sh
=> aktualizr: switch to 2020.7+fio

src/helpers.cc, src/helpers.h
This code has always been wrong and I think we were seeing curl complain
about this in the past. However, it wasn't problematic until we started
testing with SoftHSM more. The HSM needs critical sections around access
to it from a process. The KeyManager by way of the P11EngineGuard does
this. However, it does on the object instance. By sharing the instance
we get the proper locking required.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> helpers: Fix concurrency problem found with HSMs

src/composeapp.cc, src/composeapp.h, src/composeappmanager.cc, src/composeappmanager.h, src/helpers.cc, src/helpers.h, src/main.cc, tests/composeapp_test.cc, tests/docker_fake.sh
Add functionality for verification of Compose App containers status.
Status is fully checked:
- in non-daemon mode, `aktualizr-lite update`;
- on the first update cycle in daemon mode;
- if a new Target is available and about to be applied in a daemon mode.
=> Check App status and update if not running

src/CMakeLists.txt, src/main.cc, tests/CMakeLists.txt
- switch to 2020.8+fio
- adjust aktualizr-lite to aktualizr 2020.8, i.e. headers restructuring
=> aktualizr: switch to 2020.8+fio

src/composeappmanager.cc, src/composeappmanager.h, tests/compose_fake.sh, tests/composeapp_test.cc
This is the fix aimed to resume/retry a fetch or an update of Compose Apps that were not successfully fetched/updated during the previous update cycle if aklite is running in a daemon mode and no new Target. Configuration change along with aklite restart and new Target resets the given logic since a list of apps can be changed at the given circumstances.
=> Fix update resume

src/helpers.h, src/main.cc
- Output device UUID and name on `aktualizr-lite status` call.
I will add a device name printing once this PR https://github.com/foundriesio/device-gateway/pull/3/ is merged.
=> aklite: Print device UUID and name

CMakeLists.txt, src/CMakeLists.txt, src/main.cc
This is a handy feature for debug/test. Sometimes you want to "go back
in time". However, the installed-versions DB prevents this. This new
flag allows you to:
$ aktualizr-lite update --update-name 4 --clear-installed-versions
$ aktualizr-lite daemon  # will update to Target 5
=> Add ability manually install old Targets

src/composeappmanager.cc, src/composeappmanager.h, src/helpers.cc, tests/composeapp_test.cc
- If `compose_apps` is not specified in sota.toml then install all
Target's Apps;
- If `compose_apps` is specified in sota.toml then an intersection of
Target's Apps and the compose_apps' list is installed.
- The previous statement implies that an empty `compose_apps` instructs
to NOT install any Target's Apps at all.
=> Install all Target Apps if compose_apps is not specified

src/main.cc
If the check for new TUF metadata fails then wait for the TUF cycle
interval time which is specified in sota.toml. In other words, don't
start the next update cycle straight away if TUF metadata update fails,
wait for a configurable amount of time before doing it.
=> Wait for the 'interval' if metadata update fails

src/composeappmanager.cc, src/helpers.cc, src/helpers.h, src/main.cc
1) FIO OTA Lite solution does not need/support delegations, so no need in getting a target list in the way that the delegations require, specifically, using the complex iterator logic over a simple vector of target objects/json. Just simply fetch that target list as a vector.
2) At first, check if there is a new Target, and if so then proceed with new
Target update. If there is no new Target then check if the apps list changed in the config (first run) and if all current Target' apps are installed and running. There is no reason to perform current Target' apps check and sync if there is a new Target since the new Target can have a different list of apps.
=> Check for update improvements

src/helpers.cc, src/helpers.h, src/main.cc, tests/helpers_test.cc
Currently aklite doesn't allow to install Target that it tried to install previously. Even if Target installation was successful it treats it as a "bad" Target that caused rollback and doesn't allow installing it.
The given change checks Target to be installed against Targets that aklite tried to install but never installed them except pending one, which can happen only in the case of rollback.
=> aklite: allow updating to previously successfully installed Target

src/docker.cc
The logic that deduces an auth endpoint URL to get auth creds for accessing
Registry depends on the '/treehub' which makes it vulnerable to any
changes in the ostree_server conf param. The given change allows using
any prefix value, e.g. "/ostree"
=> apps: make finding of an auth endpoint prefix agnostic

src/liteclient.cc
Instead of providing the client information in the configuration class
(which describes its fundamental characteristics but not how these will
be used) we choose to provide it as a parameter to the instantiation
of the class.
=> liteclient: let storage know its client (TUF/Uptane)

tests/CMakeLists.txt, tests/device-gateway_fake.py, tests/liteclient_test.cc
Make sure that aklite sends the requests headers to Device Gateway that it uses to infer/deduce a device status.
=> Test headers aklite sends to Device Gateway

tests/CMakeLists.txt, tests/liteclient_test.cc
The following tests have been added:
OstreeUpdateWhenNoInstalledVersions
perform an update when the initial version is not available
OstreeUpdateInstalledVersionsCorrupted1
invalidate the installed_verion json by corrupting the sysroot hash
OstreeUpdateInstalledVersionsCorrupted2
write an invalid json to the filesystem
Also refactored the code a little bit to improve its readability.
=> liteclient_test: extend test suite

src/liteclient.cc, src/liteclient.h, src/main.cc, tests/liteclient_test.cc
- send a currently installed app list in a header request to the backend
unconditionally, regadles if an app shortlist specified or not;
- add tests to verify the given use-case
=> apps: send app list in a header unconditionally

src/compose/composeappmanager.cc, tests/liteclient_test.cc
- Don't start any updated apps if the rootfs/ostree update was not
successful and rollback happened during a boot;
- Add a test to cover the given use-case.
=> apps: don't start updated apps if ostree rollbacked

src/CMakeLists.txt, src/compose/composeappmanager.cc, src/helpers.cc, src/helpers.h, src/liteclient.cc, src/liteclient.h, src/main.cc, src/target.cc, src/target.h, tests/helpers_test.cc, tests/liteclient_test.cc
This is the first "cherry-pick" from the "simplification" branch https://github.com/foundriesio/aktualizr-lite/tree/refact/update-logic-simplification. It defines a new class/namespace aimed to encapsulate all Target-related functionality and decouple its clients from implementation details as well as avoid hard coding and copy-pasting. It's not fully leveraged in the given PR as its full utilization require further changes/refactoring in the code base, but will be so later.
=> Encapsulate Target-related functionality

src/compose/composeappmanager.cc
This is a regression issue, the fix just reverts back the mistakenly made change.
(my new tests, I am working on, has discovered this issue). 
=> fixup! get currently installed apps correctly

src/liteclient.cc, src/liteclient.h, src/main.cc, tests/fixtures/liteclienttest.cc
Extend a context of `check-for-update-post` callback.
RESULT is set to OK if the check is successful, otherwise, it's set to FAILED.
INSTALL_TARGET is empty if `FAILED` or no new Target nor current Target sync.
INSTALL_TARGET is set to the Target name to be installed or synced.
=> callback: extend the post check callback context

src/liteclient.cc, tests/test_lite.sh
Add/change the following in the callback context/env variables
- add CURRENT_TARGET_NAME env. variable
- rename INSTALL_TARGET to INSTALL_TARGET_NAME
=> callback: explicit Target name as callback context

src/composeappmanager.cc, src/composeappmanager.h, src/docker/docker.cc, src/docker/docker.h, src/liteclient.cc, tests/composeapp_test.cc, tests/fixtures/composeappenginetest.cc, tests/fixtures/dockerregistry.cc
Use the TUF repo (DG) URL to compose an URL to obtain creds from for Docker Registry.
Previously, the URL to Treehub/Ostree server was used for this purpose.
Since we are splitting Device Gateway into two servers, Device Gateway (TUF) and OstreeProxy then their URLs will differ and the Auth endpoint is exposed by Device Gateway/TUF server.
=> Assume TUF repo server is Hub creds provider

src/bootloader/rollbacks/masked.h
Call fw_printenv with no-header (-n) when extracting the
bootfirmware_version content, otherwise it will be printed together with
the variable name, invalidating the string comparison logic to decide
when to set bootupgrade_available to 1.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> bootloader/masked: call fw_printenv without variable name

src/bootloader/rollbacks/fiovb.h
```
Don't set bootupgrade_available flag in UpdateNotify(), as
during that step we're not able to detect if we have boot firmware
updates (this is decided conditionally in InstallNotify()).
Reported-by: Tim Anderson <tim.anderson@foundries.io>
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
```
=> bootloader: fiovb: don't set bootupgrade_available

src/liteclient.cc, src/liteclient.h, src/main.cc, tests/helpers_test.cc
The current download and update locks are not used.
Since we added the aklite system-wide lock that prevents from running two simultaneous update sessions they become obsolete/redundant.
=> Remove the download/update lock

src/appengine.h, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, tests/composeapp_test.cc, tests/composeappengine_test.cc, tests/docker-compose_fake.py, tests/liteclientHSM_test.cc, tests/liteclient_test.cc
Track App update state and make use of it, so
* network usage is optimized, aklite doesn't re-fetch what has been already fetched;
* simplify debugging and troubleshooting;
* extend the context of report events with App state info.
=> Store and make use of App update state

src/bootloader/rollbacks/fiovb.h
On a closed board, if the bootfirmware_version is not set
it means that an upgrade is need to properly set the version.
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
=> bootloader: update fw if bootfirmware_version is not set

src/main.cc
Add the dummy 'update-lockfile' cmd param for backward compatibility
with the older version of meta-lmp that starts aklite service with the
given param.
=> fixup! add dummy 'update-lockfile' param for compatibility

src/docker/composeappengine.cc
The warning message might scarry users as they appear during the transition to the latest aklite version that supports App state tracking. Specifically, if aklite is updated and one or more of the Apps are not updated then the state files won't be present on a system so isRunning() check cannot be accomplished by means of the state files. The PR just set DEBUG level for the message informing about it.
=> apps: use DEBUG level msg if no app state file

src/docker/composeappengine.cc, src/docker/composeappengine.h, tests/aklite_test.cc, tests/fixtures/composeapp.cc
Make sure that a new Target App, that akite downloads, includes a compose file (docker-compose.yml).
=> apps: check downloaded App contains a compose file

src/docker/composeappengine.cc, src/docker/composeappengine.h
Make sure that the state files exist before trying to fetch info from
them during gathering info about currently running apps and their
containers/services.
=> apps: check if the state files exist before use

src/CMakeLists.txt, src/liteclient.cc, src/rootfstreemanager.h
- Add ability to run aklite on a local host in the case of `ostree`
package manager usage. I.e. teach the ostree manager to manage a
standalone/non-booted ostree-based rootfs.
- Also, it makes the ostree package manager use the Fio's bootloader instead of the
libaktualizr's native one. The bootloader update won't work if the
libaktualizr's bootloader implementation is used.
=> aklite: add ability to manage non-booted rootfs

src/CMakeLists.txt, src/composeappmanager.cc, src/composeappmanager.h, src/ostree/repo.cc, src/rootfstreemanager.cc, src/rootfstreemanager.h
Pull ostree commit objects from directly from the GCS bucket(s). If remotes that points to the buckets are not available or pull from GCS fails then fallback to fetching via Device Gateway or OSTreeproxy, depending on the device/aklite configuration.
=> ostree pull from GCS with fallback to DG/ostreeproxy

CMakeLists.txt, examples/CMakeLists.txt, examples/custom-client.cc, include/aktualizr-lite/api.h, src/CMakeLists.txt, src/api.cc, src/liteclient.cc, src/liteclient.h, tests/CMakeLists.txt, tests/apiclient_test.cc, tests/device-gateway_fake.py, tests/fixtures/liteclient/devicegatewaymock.cc
This patchset introduces an easy-to-use API into aktualizr-lite to allow users to produce their own custom daemons with specialized logic for controlling how updates are processed.
The API is currently missing support for ComposeApps as well as support for managing secondary ECUs. These will come in future changes once this initial API is agreed on.
=> Add new aktualizr-lite API

examples/custom-client.cc, include/aktualizr-lite/api.h, src/api.cc, src/liteclient.cc, src/liteclient.h, tests/apiclient_test.cc, tests/device-gateway_fake.py, tests/fixtures/liteclienttest.cc
This patchset allows custom clients to define and manage secondary ecus in the way that works best for them. The API doesn't specify mechanism, it simply provides APIs to inform the Foundries device-gateway the status of secondary ecus.
=> Add support for secondary ecus via custom api

src/CMakeLists.txt
=> api: Include jsoncpp headers with install

src/CMakeLists.txt
This reverts commit 87fde29d993f457fa304c4467132d698d6dac523.
Turns out the better way of handling this in OE is to depend on the
jsoncpp package:
https://github.com/foundriesio/meta-lmp/pull/430#discussion_r714812071`
=> Revert "api: Include jsoncpp headers with install"

CMakeLists.txt, docker/Dockerfile, src/CMakeLists.txt, src/appengine.h, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/composeinfo.cc, src/docker/composeinfo.h, src/docker/docker.cc, src/docker/docker.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/target.h, tests/CMakeLists.txt, tests/aklite_test.cc, tests/apiclient_test.cc, tests/composeappengine_test.cc, tests/docker-daemon_fake.py, tests/docker-registry_fake.py, tests/fixtures/composeapp.cc, tests/fixtures/composeappenginetest.cc, tests/fixtures/dockerdaemon.cc, tests/fixtures/dockerregistry.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc, tests/restorableappengine_test.cc
- Use `skopeo` to pull images from Registry(ies);
- Store apps&images' data (manifests, blobs, etc) in dedicated folder/volume in addition to `/var/lib/docker` and `/var/sota/compose-apps`;
- Use skopeo to copy images from the restorable app store to the docker store (`/var/lib/docker');
- If `/var/lib/docker` and `/var/sota/compose-apps` are removed then Apps&images are restored from the local store.
=> Restorable apps

src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/fixtures/dockerregistry.cc, tests/restorableappengine_test.cc
Make sure that App content (manifest and/or its archive) is (re-)fetched only if it's not stored or damaged (hash) on a file system.
=> Skip App fetching if already fetched

src/docker/docker.cc, src/docker/docker.h, src/docker/restorableappengine.cc, tests/fixtures/composeapp.cc
- store a received App manifest as it is, don't apply any modification/canonization;
- calculate a manifest hash by using actual unmodified/non-canonized  representation of an App manifest json;
- minor logging improvement.
=> Fix app manifest storing and verification

docker/Dockerfile, src/appengine.h, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/aklite_test.cc, tests/apiclient_test.cc, tests/docker-compose_fake.py, tests/fixtures/composeapp.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc, tests/restorableappengine_test.cc
Make sure that App is verified (docker-compose config) just after successful download.
We used to do it for Compose Apps at the end of "fetch" phase.
Now, we want to support App update rollback, so we need to distinguish between true download and Target verification&installation  failures. In the first case, aklite can keep doing download attempts to make sure that Target Apps are fully downloaded. In the later case, there is no sense in update retrying, thus a rollback should be performed.
=> Add Target verification step to Compose App Manager

include/aktualizr-lite/api.h, src/api.cc
When clients run in a daemon mode, they'll need to assert they are the
only copy of the process running. Tools like lmp-device-register also
check for this.
=> api: Add option to assert single instance

src/api.cc, tests/apiclient_test.cc
The backend will now track hwid's if provided.
=> api: Include secondary hwid in backend payload

CMakeLists.txt, tests/CMakeLists.txt
Add the HSM specific test suite of aklite conditionally, only if BUILD_P11 is turned ON.
=> cmake: include HSM specific test conditionally

src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/aklite_test.cc, tests/docker-compose_fake.py, tests/fixtures/composeapp.cc
This change makes sure that we properly determine whether a new App was successfully installed or not.
From aklite (update agent) perspective an App installation is successful if:
1.  `docker-compose up` exits with 0;
2.  All App's containers are created.
So, the PR makes sure the second criterion is met.
App/service running inside of Compose App's container(s)  might fail of course, too. But aklite doesn't take it into account during App installation since this is App specific business logic failure and we wanna keep aklite agnostic of it.
Thus, in this case, a user will be notified that the new App version was successfully installed, but the status report will indicate that one or more of the App's containers are not running including its state and exit/failure code&reason.
=> Check if App is really installed successfully

src/api.cc
This is an issue in particular after restarting and trying to report that a Secondary has completed installation before checking for new updates. A segfault would occur in `AkliteClient::Installer()` via `LiteClient::allTargets()` when trying to fetch targets from an empty shared pointer.
Note that this fixes the bug on the client side, but the web UI shows the successful installation completed event in a separate chain of events from the rest, presumably because the correlation ID is different. I'm not quite sure how to fix that, and that's not quite as important to me yet, although it would be good to fix.
=> Make sure the metadata is loaded from storage before trying to use it.

include/aktualizr-lite/api.h, src/api.cc, tests/apiclient_test.cc
In certain advanced cases, a custom client might need to re-use a
correlation ID to group events together in the backend.
=> api: Add ability to set correlation ids

src/docker/docker.cc, src/docker/docker.h, src/docker/restorableappengine.cc, tests/composeapp_test.cc, tests/fixtures/composeapp.cc, tests/restorableappengine_test.cc
We do not know in advance a size of an App's index/root manifest,
hence we just assume that it shouldn't be bigger than certain predefined value (16KB).
But, we know a layer manifest size since it is defined in the root level manifest (Merkle tree).
Therefore, we must ensure that a downloaded layer manifest's size matches the size specified in the root manifest.
Also, we must sure that data being downloaded don't exceed the given manifest's size,
libcurl does that we just pass a corresponding param down to it via the http client.
=> apps: check expected size of a layer manifest

src/composeappmanager.cc, src/composeappmanager.h, tests/aklite_test.cc, tests/fixtures/dockerdaemon.cc, tests/fixtures/liteclienttest.cc
- Add a config param `create_containers_before_reboot` that allows
configuring aklite behavior if both ostree and Apps are updated.
Specifically, whether to recreate App's containers or not before a system reboot.
By default, App's containers are recreated (but not restarted).
It's worth noting that App containers are recreated just after reboot if
docker-compose detects any configuration changes in any case
(e.g. a new version of ostree/LmP modifies compose App content on boot).
=> apps: parameterized App recreation before reboot

src/liteclient.cc, src/liteclient.h, src/main.cc
- Invoke `check-for-update-post` callback in any case, including the case when an exception occurs.
- If a target is not found for a given device (hw ID and tags) while the metadata update is successful then do not treat it as an exceptional situation.
- Improve logging for the use-cases related to updating of metadata and finding the latest target for a device.
=> aklite: invoke the post check callback in any case

src/composeappmanager.cc, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/aklite_test.cc, tests/fixtures/dockerdaemon.cc, tests/restorableappengine_test.cc
Check whether there is sufficient amount of available storage in both the skopeo and docker store before an App update.
A storage size, required to accommodate a new App version, is calculated  precisely for the skopeo store (tar.gzip format) and approximately for the docker store.
The approximation is based on an average gzip compression ratio in the case of rootfs diffs/image layers.
=> Check an available capacity of the docker store before an App update

src/composeappmanager.cc, src/docker/composeappengine.cc, src/helpers.cc, src/liteclient.cc, src/liteclient.h, src/main.cc, src/ostree/sysroot.cc, src/ostree/sysroot.h, src/rootfstreemanager.cc, src/rootfstreemanager.h, tests/aklite_test.cc, tests/apiclient_test.cc, tests/composeapp_test.cc, tests/docker-compose_fake.py, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc
1. If Apps fails to start just after successful boot on a new sysroot version (just sysroot update or both sysroot & Apps update):
1.1 Mark the given Target as a failing Target (aka "known").
2.2 Initiate rollback to the previously successfully installed Target, provided that there is such Target (two failing Targets/updates in a row).
2. If Apps (re-)creation fails before reboot (both sysroot and Apps update) then:
2.1 Mark the given Target as a failing Target (aka "known").
2.2 Undeploy currently pending sysroot by reinstalling the previously successfully installed Target (kind of Target sync).
=> Rollback if Apps fail to create before reboot or start after reboot

src/liteclient.cc, src/liteclient.h, tests/liteclient_test.cc
Make sure that Targets are initialized at an image repo, so
the corresponding shared ptr is not null. If it is null then
just return an empty array of targets.
=> fixup! check targets are initialized before usage

.gitmodules, examples/custom-client-cxx/main.cc, tests/apiclient_test.cc, tests/fixtures/liteclient/tufrepomock.cc, tests/fixtures/liteclienttest.cc
Allow updating metadata if local and remote versions are the same
but they actually differ.
We need it for the use-case of switching tags on a device what may lead
to a need to update metadata of the same version.
Each tag has its own set of metadata (except root) so metadata
of different tags can have the same version but they actually differ
because they refer to different set of targets.
=> aktualizr: allow updating meta if the same ver

src/liteclient.cc, src/main.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc
Enforce an ostree update if current and the latest targets have different ostree hashes even if their versions match.
This is needed for the use-case when the same OE CI run is re-run one or more times and each time a new ostree and target are pushed to the backend.
=> ci-retest aklite: enforce ostree update if hashes differ

CMakeLists.txt, include/aktualizr-lite/api.h, src/CMakeLists.txt, src/api.cc, src/appengine.h, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/downloader.h, src/exec.h, src/liteclient.cc, src/liteclient.h, src/main.cc, src/rootfstreemanager.cc, src/rootfstreemanager.h, src/target.cc, src/target.h, tests/CMakeLists.txt, tests/aklite_test.cc, tests/apiclient_test.cc, tests/composeapp_test.cc, tests/exec_test.cc, tests/fixtures/dockerregistry.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc, tests/test_lite.sh
This PR goal is twofold, report download error messages and make the first step towards getting rid of dependency on the package manager interface.
- Introduce a new interface of a target download that uses the api's download result type.
- Make the package managers implement the new interface.
- Change LiteClient so it uses the new download interface and includes a failure reason into a report event sent to the backend.
- Adjust LiteClient clients so they use the api's download result type.
=> Change the target download interface

src/appengine.h, src/composeappmanager.cc, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/liteclient.cc, tests/aklite_test.cc, tests/apiclient_test.cc, tests/device-gateway_fake.py, tests/fixtures/liteclienthsmtest.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc
- Catch `docker-compose up [--no-start]` stderr and include it
into the install complete report event.
- Extend/adjust existing tests so they check whether the App start
error message is cacthed and included into the event.
=> aklite: include App start err into report event

CMakeLists.txt, src/docker/docker.cc, src/docker/docker.h, src/docker/restorableappengine.cc, tests/CMakeLists.txt, tests/aklite_test.cc, tests/docker-registry_fake.py, tests/docker_test.cc, tests/fixtures/composeapp.cc, tests/restorableappengine_test.cc
- Fix Docker::Uri::parseUri implementation so it accepts image URIs
that contains one or more elements in the `name` (aka `path`) field
of an image URI. E.g. fiotesting1.azurecr.io/alpine@sha256:<hash>,
fiotesting1.azurecr.io/library/alpine/latest@sha256:<hash>.
- Extend existing tests so they verify images referred by different
and acceptable URI formats.
- Add new unit test to cover the image URI parsing logic.
=> docker: align image URI parsing with OCI dist spec

docker/Dockerfile, src/composeappmanager.cc, src/composeappmanager.h, unit-test
Switch from the python based `docker-compose` to golang based
`docker compose` owned by docker org.
=> apps: Use `docker compose` by default

include/aktualizr-lite/api.h, src/appengine.h, src/composeappmanager.cc, src/docker/restorableappengine.cc, src/liteclient.cc, src/main.cc, src/rootfstreemanager.cc, tests/fixtures/liteclient/sysostreerepomock.cc, tests/liteclient_test.cc, tests/restorableappengine_test.cc
- Identify an insufficient space error if ostree or restorable App pull fails;
- Don't retry the pull if such the error is detected;
- Don't try new updates until aklite is restarted (or device is rebooted).
=> No space reaction

include/aktualizr-lite/api.h, src/liteclient.h, src/main.cc, src/rootfstreemanager.cc, tests/fixtures/liteclienttest.cc
aklite: Skip update download if failed before
Skip an attempt to download an update/Target if:
1) its ostree download failed before due to lack of free space;
2) size of free space has not increased since the failure time.
=> Skip update if download failed before

src/appengine.h, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/apiclient_test.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc
Apps that have been removed from a config or are not present in a new
Target should be stopped before creating/starting new Apps because they
may interfere with each other, e.g. the same port is re-used.
- Add a new method to AppEngine to stop App.
- Stop removed Apps before creating and/or starting new Apps.
=> apps: stop removed Apps before creating new one

src/api.cc, src/liteclient.cc, src/liteclient.h, src/main.cc, src/offline/client.cc, src/offline/client.h, tests/fixtures/liteclient/tufrepomock.cc, tests/fixtures/liteclienthsmtest.cc, tests/fixtures/liteclienttest.cc
Import pre-provisioned root role metadata from a file system into the
aklite's DB if:
- no any root meta found in DB;
- root meta are found on a file system.
The import procedure detects whether it's a prod or CI device and imports correspondent root metadata.
=> aklite: Import pre-provisioned root meta

Makefile, docker/Dockerfile, include/aktualizr-lite/api.h, src/api.cc, src/docker/composeappengine.h, src/docker/docker.cc, src/docker/docker.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, src/docker/restorableappengine.cc, src/liteclient.cc, src/main.cc, src/ostree/sysroot.cc, src/rootfstreemanager.h, src/target.cc, tests/CMakeLists.txt, tests/composeapp_test.cc, tests/fixtures/composeapp.cc, tests/fixtures/liteclienthsmtest.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc
Switch to the latest version of libaktualizr and adjust aklite to it.
Relevant changes in libaktualizr:
- 6fc8e722 Upgrade to clang-format-11 (and friends)
- 388a50eb [fio extras]: add 'length' and 'hashes' to snapshot
- 9d3ee3ae [fio extras]: allow updating meta if the same ver
- 9a298772 Remove STORAGE_TYPE option from CMakeLists and tests
- 068ea357 [fio extras]: httpclient: follow redirects by default
- 1b6e9ae2 http: Remove redundant curl options
- d2ab5e51 Add test for extra keys in root.json
- 3cb7e2a2 scripts: Fix the script to run tests in docker
- caf558b2 docker: Create a home directory of the test user
- 81ab71da crypto: Make the p11 engine singleton within a test suite
- bf0494df Speed up compiles with Include What You Use
- 07937a70 tuf-test-vectors: Test update if metadata …
=> Switch to the latest version of libaktualizr

src/composeappmanager.cc, src/composeappmanager.h, src/liteclient.cc, src/liteclient.h, tests/composeapp_test.cc
Send Apps status to Device Gateway only if it has changed since the last time it was checked.
=> aklite: Send Apps status only if changed

src/liteclient.cc, src/liteclient.h, tests/fixtures/liteclienttest.cc
- Add ability to limit a number of events to include into a single
request to Device Gateway.
- Limit event number sent in a single HTTP POST /events request.
- Handle 413 response to HTTP POST /events request by re-trying with
fewer events in a body until just one event is sent.
- If 413 to a request that carries just one event then just drop the
event and stop trying to send it.
- Add unit tests for the aforementioned functionality.
=> aklite: Limit event number sent to Device Gateway

src/composeappmanager.cc, src/rootfstreemanager.cc, src/rootfstreemanager.h
This fixes the setting of bootloader variables when using:
type = ostree
Signed-off-by: Michael Scott <mike@foundries.io>
=> rootfstreemanager: make sure to call updateNotify and installNotify

src/bootloader/bootloaderlite.cc, src/bootloader/bootloaderlite.h, src/bootloader/rollbackfactory.cc, src/bootloader/rollbacks/factory.h, src/bootloader/rollbacks/fiovb.h, src/bootloader/rollbacks/masked.h, src/bootloader/rollbacks/rollback.h, src/ostree/sysroot.cc, src/ostree/sysroot.h, src/rootfstreemanager.h, tests/fixtures/liteclient/fiovb.cc, tests/fixtures/liteclienthsmtest.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc
- Enable testing of the bootloader flag management in each liteclient test.
- Enable testing of the `ostree` package manager along with the composite one (`ostree+compose_apps`).
=> Test the bootloader flag management and ostree package manager

src/appengine.h, src/containerd/client.cc, src/containerd/client.h, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, src/docker/restorableappengine.cc, tests/docker-daemon_fake.py
appengine: Move pruning to an engine client impl
Don't call the image and container pruning commands directly from an app
engine. Instead, do it indirectly via the app engine client interface.
A specific implementation of the pruning is encapsulated within a
specific implementation of a container engine client.
=> Image and container pruning

src/offline/client.cc
Make sure the docker client path/file exists before its usage.
This is workaround to make the aklite-offline work on a device that does not include /usr/bin/docker but has dockerd.
=> aklite-offline: Check the docker client path

apps/aklite-offline/cmds.cpp, src/offline/client.cc, src/offline/client.h
Make sure the docker client path/file exists before its usage.
1. This is workaround to make the `aklite-offline` work on a device that does not include `/usr/bin/docker` but has `dockerd`.
2. More accurate support of just ostree update if docker installed or no Apps are present in the offline update content.
=> aklite-offline: Support update if no Apps or dockerless system

src/composeappmanager.cc
Prune containers and images of removed Apps only if `docker_prune` is enbaled in the aklite config.
=> apps: Prune images only if pruning is enabled

src/bootloader/bootloaderlite.cc, src/bootloader/bootloaderlite.h, src/rootfstreemanager.cc, src/rootfstreemanager.h, tests/aklite_rollback_test.cc, tests/fixtures/liteclient/boot_flag_mgr.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc
Ban ostree update if there is ongoing boot fw update and implicitly initiate device reboot by returning the `need completion` return code. The reboot is need to confirm and finalize the boot fw update.
=> boot: Block update if boot fw update is in progress

src/api.cc, src/composeappmanager.cc
Stop the updated containers before reboot so they are not automatically
started by `dockerd` just after reboot. `aklite` is going to re-create
and start them during the update finalization.
=> Stop updated containers before reboot

include/aktualizr-lite/api.h, src/api.cc, src/appengine.h, src/composeappmanager.cc, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/liteclient.cc, tests/aklite_test.cc, tests/docker-compose_fake.py, tests/fixtures/dockerdaemon.cc, tests/restorableappengine_test.cc
Run `docker-compose pull` for each installed App before creating or starting App. The pull command updates the docker store so it becomes aware of the App images. As result, the following `compose up` command won't require network connection to pull any App image data. It helps to distinguish between networking errors and pure container creation or start errors. The first one is NOT critical hence aklite should continue trying to install App. The second error type is critical and aklite should mark corresponding Target as "failing" in such the case.
=> apps: Docker pull images just after App install

src/liteclient.cc
Add a new callback and invoke it just before running the install finalization procedure. It allows clients to be notified about the beginning of the final stage of the update installation that happens just after reboot.
=> Invoke callback just before install finalization

src/docker/docker.cc, src/offline/client.cc
Return HTTP 404 with the file path if the requested App blob is missing in the specified source directory.
=> offline-client: Return 404 if requested blob is missing

src/offline/client.cc, src/offline/client.h
Don't initialize and pass around the docker client's default http client within the offline updater, instead, do nothing as the docker client initializes the default one by itself if no custom http client is specified in its ctor.
=> offline: Fix dockerless system support

apps/aklite-apps/cmds.cpp, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/offline/client.cc
offline: Don't pull images at App start
By default, aklite/restorable-engine tries to pull images at App start
to distinguish between download and install failure during target
installation. E.g. if a device goes offline just after App download and
before installation then install will fail because it cannot check App
image manifest at Registry. Having ability to distinguish between fetch
and a real install failure allows aklite to keep target install retrying
if it is just fetch failure.
But it does not work for the offline client and the early app startup
because a device is really offline and it is assumed that all App data
are already preloaded, so no need to do `compose pull` at App startup.
Otherwise, it will just fail since `compose pull` tries to fetch an
image manifest regardless …
=> offline: Don't pull images at App start

examples/custom-client-cxx/main.cc, include/aktualizr-lite/api.h, src/api.cc
When `pacman.create_containers_before_reboot = 0`, we can hit issues where containers fail to get created upon the reboot after an OTA. In this scenario we need to rollback to the old Target.
=> custom client: Handle rollback for failed apps

apps/aklite-offline/cmds.cpp, src/liteclient.cc, src/liteclient.h, src/offline/client.cc, src/offline/client.h, src/rootfstreemanager.h, tests/aklite_offline_test.cc, tests/fixtures/liteclient/boot_flag_mgr.cc
- Detect and inform a client about a boot firmware update and a need in a device reboot to confirm such the update.
- Add tests to cover the boot  firmware update case.
=> Offline update with boot fw update

src/bootloader/bootloaderlite.cc, src/bootloader/bootloaderlite.h, src/ostree/repo.cc, src/ostree/repo.h, src/rootfstreemanager.cc, src/rootfstreemanager.h, tests/CMakeLists.txt, tests/aklite_offline_test.cc, tests/apiclient_test.cc, tests/boot_flag_mgmt_test.cc, tests/fixtures/liteclient/boot_flag_mgr.cc, tests/fixtures/liteclient/ostreerepomock.cc, tests/fixtures/liteclient/sysostreerepomock.cc, tests/fixtures/liteclient/sysrootfs.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc, tests/ostree_test.cc
- Tests&Fixtures refactoring.
- Reject update if bootloader rollback is detected and rollback protection is turned on.
- Add tests for the rollback protection.
=> Bootloader rollback protection

src/bootloader/bootloaderlite.cc, src/bootloader/bootloaderlite.h, src/rootfstreemanager.cc, tests/boot_flag_mgmt_test.cc, tests/fixtures/liteclient/boot_flag_mgr.cc, tests/fixtures/liteclienttest.cc
- Allow any format of a bootloader version if no rollback protection.
- Proceed with update if a version file is not found in a new target.
- Reject update if new bootloader version is malformed.
- Proceed with update if the current bootloader version is not set (env var) or is malformed provided that a new version is correct.
=> Handle egde cases of bootloader update

src/liteclient.cc
Make sure all report events are sent to Device Gateway at the beginning of the liteclient instance destruction.
=> liteclient: Drain events before destruction

Makefile, README.md, dev-flow.mk, examples/custom-client-cxx/main.cc
- Add the custom client target.
- Add env var to specify config dir for the custom client.
- Add info to `README` on building and running the custom client example.
=> Custom client target

src/docker/restorableappengine.cc, src/docker/restorableappengine.h
Override the default value of the skopeo's maximum parallel/concurrent pulls if the env. var. `SKOPEO_MAX_PARALLEL_PULLS` is set to a value in the allowed range [1, 10].
If `SKOPEO_MAX_PARALLEL_PULLS` is not defined, then `skopeo` will apply the default value which is `3` for LmP and `6` for other use-cases.
=> Skopeo parallel pull control

src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/restorableappengine_test.cc
Remove tmp files created by skopeo during image layer pulling that are not cleaned up if `skopeo copy` is interrupted. 
The cleanup function is called only at the aklite initialization since tmp files are not removed by skopeo only if an overall process is interrupted/killed/device is rebooted.
=> Cleanup skopeo's tmp files

apps/aklite-offline/cmds.h
Translate the input source path into the absolute path because the ostree won't be able to pull if a path is relative.
=> offline: Use absolute path to source dir

CMakeLists.txt
Add CMake build param to to turn ON/OFF the `aklite-apps` building.
=> cmake: Add build param to turn ON/OFF aklite-apps

src/docker/docker.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/fixtures/composeapp.cc, tests/fixtures/dockerregistry.cc, tests/restorableappengine_test.cc
This change enables aklite to utilize App layers metadata that contains precise disk usage information for each layer. As a result, aklite can calculate the App update size with a high level of accuracy. There are additional metadata that the docker store utilizes for each layer size/usage that are not considered by aklite. The overall size of these metadata does not depend on the layer size and is not significant.
If the App layers metadata is not found, aklite will fall back to an approximate calculation of the App update size.
=> apps: Calculate App update size precisely

src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/yaml2json.cc, tests/aklite_rollback_test.cc, tests/apiclient_test.cc, tests/device-gateway_fake.py, tests/fixtures/liteclient/devicegatewaymock.cc, tests/fixtures/liteclienttest.cc, tests/yaml2json_test.cc
I was informed about the following error a few times:
```
Jul 11 20:01:04 stm32mp15-disco-3d00383338510b39303435 aktualizr-lite[920]: Checking Active Target status...
Jul 11 20:01:04 stm32mp15-disco-3d00383338510b39303435 aktualizr-lite[920]: App: shellhttpd, cannot check whether App is running: * Line 1, Column 1
Jul 11 20:01:04 stm32mp15-disco-3d00383338510b39303435 aktualizr-lite[920]:   Syntax error: value, object or array expected.
Jul 11 20:01:04 stm32mp15-disco-3d00383338510b39303435 aktualizr-lite[920]: shellhttpd update will be re-installed or completed
```
After investigation, I came to conclusion that that error message can appear only if `docker-compose.yml` is empty and produced by the `yaml2json` component. The `fy-tool` doesn't produce error if an input `yaml` file is …
=> Improve app storing and parsing

src/rootfstreemanager.cc, tests/CMakeLists.txt, tests/fixtures/fstatvfs-mock.cc, tests/fixtures/liteclient/ostreerepomock.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc
There is no point in continuing to attempt pulling static delta files if the pull error indicates that there is not enough storage space to accommodate them.
This change detects the delta pull error caused by a lack of storage space and instructs aklite to set a state where it won't attempt to pull the current target until more space becomes available.
=> ostree: Exit fetch retry loop if no space while pulling deltas

src/rootfstreemanager.cc, src/rootfstreemanager.h, tests/boot_flag_mgmt_test.cc, tests/cli_test.cc, tests/fixtures/liteclient/sysostreerepomock.cc, tests/fixtures/liteclienttest.cc, tests/nospace_test.cc
- Pull delta statistics for a given update if available.
- If available, then check if there is enough free storage available
taking into account the storage watermark.
- Don't pull update/ostree if there is not enough free storage available
and exit with the corresponding error.
- Add unit tests for the given use-case.
=> Delta stat application: check update size before fetching update data

src/CMakeLists.txt, src/composeappmanager.cc, src/ostree/sysroot.cc, src/ostree/sysroot.h, src/rootfstreemanager.cc, src/rootfstreemanager.h, src/storage/stat.cc, src/storage/stat.h, tests/fixtures/fstatvfs-mock.cc, tests/fixtures/liteclient/ostreerepomock.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc, tests/nospace_test.cc
- Add functionality to obtain storage usage that can be used across all use-cases.
- Apply the new storage usage obtaining functionality to all ostree pull use-cases, with and without delta, negative and positive cases.
- Extend and improve the unit tests to verify the new and modified functionality.
=> Unify and improve free space verification

src/api.cc, src/composeappmanager.cc, src/composeappmanager.h, src/downloader.h, src/liteclient.cc, src/liteclient.h, src/main.cc, src/rootfstreemanager.cc, src/rootfstreemanager.h, src/storage/stat.cc, src/storage/stat.h, tests/nospace_test.cc
Extend the download result context to include storage usage information
and the amount of free space required for an ostree update.
Utilize the storage usage info and the required space value obtained in
the "no space" download result to determine whether to attempt another
pull. If there is still insufficient free storage space to accommodate
the specified ostree update, then skip the update attempt.
=> Use usage stat to controll pull attempts

src/ostree/sysroot.cc, src/ostree/sysroot.h, src/rootfstreemanager.cc, src/rootfstreemanager.h, tests/liteclient_test.cc, tests/nospace_test.cc
Remove the knob to configure the reserved amount of storage for the delta-based update. Instead, use the `min-free-space-percent` value set in ostree repo config. This param value can be overridden in the sota toml configuration -
`[pacman]:sysroot_ostree_reserved_space_percentage`.
=> sysroot: Remove redundant conf param

src/liteclient.cc
Update aktualizr reference and update aklite to use new `HttpClientWithShare` class.
=> Enable TLS connections sharing

src/appengine.h, src/containerd/client.cc, src/containerd/client.h, src/docker/docker.cc, src/docker/docker.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, src/liteclient.cc, tests/CMakeLists.txt, tests/docker-compose_fake.py, tests/docker-daemon_fake.py, tests/docker_test.cc, tests/fixtures/composeapp.cc, tests/fixtures/dockerdaemon.cc
Replace the `skopeo copy` command with the functionality that makes `HTTP POST /images/load` request to the docker daemon.
The `skopeo copy` command has two issues:
1. It implies copying layers from the skopeo store to the docker's temporal directory prior to starting layer exporting/load process.
2. It does the layer copy to the temporal directly even if those layers are already present in the docker store (because it sends the load manifest after copying all image layers...).
By extending the image load manifest with addition field that refers to the image layers blob/root directory it makes the docker loader/tarexporter to pull layer blobs directly from the skopeo/OCI store. See this PR https://github.com/foundriesio/meta-lmp/pull/1288 for details. Also, this approach automatically …
=> apps: Improve image load to docker store

src/rootfstreemanager.cc, tests/CMakeLists.txt, tests/aklite_offline_test.cc
The fioctl command that downloads content for offline update does not fetch the delta stat if the one is present for a given target. Therefore, the offline update client should not attempt to fetch the delta stat file.
=> rootfsmanager: Don't pull delta stat if offline update

apps/aklite-offline/cmds.cpp, apps/aklite-offline/cmds.h, apps/aklite-offline/main.cpp
This new command prints the current target, ostree hash and list of enabled applications, using the following format:
Target: <target>
Ostree hash: <hash>
Apps:
<app1_name> -> <app1_uri>
<app2_name> -> <app2_uri>
=> offline: Add "current" subcommand

apps/aklite-offline/main.cpp
The command line  option for log level in aklite-offline does not match the one used in aktualizr ("log-level" vs "loglevel"). Libaktualizr sets the log level regardless of the running application, and assumes a "loglevel" option is set in the program options map. This patch adds a "loglevel" entry to the map, copying the "log-level" value.
=> offline: Fix --log-level option

apps/aklite-offline/cmds.cpp, apps/aklite-offline/cmds.h, src/offline/client.cc, src/offline/client.h, src/target.h
Prevent accidental downgrades during offline updates by disallowing them by default.
Introduce a new Command Line Interface (CLI) option `--force/-f` to enable forced downgrades, empowering users to enforce updates even if the current version is higher than the specified one.
This change ensures a more controlled update process and enhances user flexibility.
=> Control offline update downgrade

include/aktualizr-lite/api.h, src/CMakeLists.txt, src/api.cc, src/cli/cli.cc, src/cli/cli.h, src/composeappmanager.cc, src/composeappmanager.h, src/installer.h, src/liteclient.cc, src/liteclient.h, src/main.cc, src/rootfstreemanager.cc, src/rootfstreemanager.h, tests/apiclient_test.cc
- Add a generic mechanism to support different installation modes. It includes adding a new `Installer` interface which along with the `Downloader` interface will eventually help to get rid of dependency on the aktualizr's PackageManager interface.
- Added "ostree only"/"delayed App installation" installation mode support.
- Added a new CLI parameter to the CLI command to turn on the delayed app installation mode.
=> api: POC: add installation modes

CMakeLists.txt, apps/tufctl/CMakeLists.txt, apps/tufctl/main.cpp, include/aktualizr-lite/api.h, include/aktualizr-lite/tuf/tuf.h, src/CMakeLists.txt, src/api.cc, src/tuf/akhttpsreposource.cc, src/tuf/akhttpsreposource.h, src/tuf/akrepo.cc, src/tuf/akrepo.h, src/tuf/localreposource.cc, src/tuf/localreposource.h, tests/apiclient_test.cc
The API allows a better isolation between aktualizr-lite and libaktualizr, and also allows the use of multiple sources for a same TUF repository.
Changes were originally submitted in #279
=> Add a TUF API to aklite

apps/aklite-offline/cmds.cpp, src/offline/client.cc, src/offline/client.h, tests/aklite_offline_test.cc
The recent [patch](https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-base/recipes-containers/docker/files/0001-tarexport-optimize-image-loading-on-local-host.patch) to the docker engine makes its restart redundant since app images are correctly registered at the end of the image loading process.
=> offline: Don't require docker restart if just app update

src/composeappmanager.cc, src/composeappmanager.h, src/offline/client.cc, tests/aklite_offline_test.cc
It is unsafe to employ "content-based" shortlisting due to the potential risk of installing unwanted targets or unintentionally removing necessary apps.
The proposed alternative mandates that all enabled/configured apps listed in the target must be present in the update source bundle, specifically the intersection of pacman.compose_app and target.apps. This ensures that a device is updated with the anticipated ostree and apps as defined by the target JSON and device configuration.
It's worth noting that there might be scenarios where multiple targets share the same ostree and the app intersection. This is not problematic as the update content remains consistent across these targets. The only drawback is that the offline updater might display an unexpected target name in the logs, …
=> offline: Require all enabled apps for offline update

CMakeLists.txt, examples/custom-client-cxx/main.cc, include/aktualizr-lite/api.h, src/api.cc, src/liteclient.cc, src/liteclient.h, src/rootfstreemanager.cc, tests/CMakeLists.txt, tests/aklite_offline_api_test.cc, tests/apiclient_test.cc
Add a new LocalLiteInstall class, that inherits from the original
LiteInstall class, overriding the Download method, making it copy target
data locally instead of fetching it remotelly.
The implementation is strongly based on the standalone offline client
code.
---
Unit tests still need to be adjusted, specially `CheckInLocal` that  now requires apps and ostree data in order to accept a target as valid.
There is an ongoing discussion about `CheckAppsInSync`. Perhaps it does not need to receive a source path in the offline case, as reset-apps would be accessed instead.
=> api: Add offline target installation

apps/aklite-offline/cmds.cpp, include/aktualizr-lite/cli/cli.h, src/api.cc, src/cli/cli.cc, src/main.cc, tests/aklite_offline_test.cc
Don't enforce the "ostree only" installation mode for an offline update. Instead, let a user/client decide which of the installation modes to apply.
=> cli: offline: Let client to decide on install mode

include/aktualizr-lite/tuf/tuf.h, src/api.cc, tests/aklite_offline_test.cc, tests/apiclient_test.cc
Strengthen target check before starting installation:
- make sure the target specified to the installer matches the one that is found in the local TUF repo;
- make sure the target specified to the local installer is available locally - its content is found in the specified local folder during the check-in phase.
=> Strengthen target check before starting installation

apps/aklite-offline/cmds.h, src/api.cc, src/liteclient.cc, src/liteclient.h, tests/test_lite.sh
- Fix offline update for non-registered devices
- Don't allow offline update if the provided TUF meta are invalid even if a local/cached one are valid.
- Fix error printing if the specified source directory doesn't exist.
=> Offline update corner case fixes

src/api.cc, src/composeappmanager.cc, tests/apiclient_test.cc
[Creating a new PR since the current solution is very different (code wise) to the original PR #300.]
These are the changes required to support a standalone install operation. They allow apps to be installed properly, and the installation to fail at the right time when the target was not pulled.
A subsequent PR will include the custom client commands allowing a standalone install operation.
=> Allow install to be called independently of pull - V2

apps/aklite-offline/cmds.cpp, examples/custom-client-cxx/CMakeLists.txt, examples/custom-client-cxx/cli.cpp, examples/custom-client-cxx/cli.h, examples/custom-client-cxx/cmds.h, examples/custom-client-cxx/daemon.cpp, examples/custom-client-cxx/main.cpp, include/aktualizr-lite/cli/cli.h, src/cli/cli.cc, tests/aklite_offline_test.cc
Original running mode now invoked with `custom-sota-daemon`.
Added commands: `check`, `pull`, `install`, `run`.
---
Items for discussion:
- I did not use AkLiteClient (cli.cc) methods, but copied over code from there. We could use `cli.cc`, but from what I understand, methods provided by `api.cc` are the interface for a customized client. If we start to officially provide `cli.cc` methods to external users, that must be a well though decision, as the behavior and signature of `cli.cc` methods should not be changed anymore.
- I avoided code reuse between different commands code. That is to simplify custom solution by users, simply taking one command code and changing it.
- I did not add `log-level` cmd option, but is not hard to add.
- See a few TBD comments bellow, if it is OK to return …
=> custom-client: Add additional running modes, with separate commands

src/api.cc, src/liteclient.cc
There is no point in attempting to send update events in the case of an offline update. Sending events during the download and install phases is prevented by overriding the input configuration, specifically by setting the TLS server URL to an empty string.
Unfortunately, applying the same workaround to the finalization phase is not feasible since there is no update-specific "installer" instance available. This change ensures that the client does not send update events during the finalization phase by checking the target custom field, which is only present in an offline update.
=> api: Don't send events if offline update

src/docker/restorableappengine.cc, tests/aklite_rollback_test.cc, tests/aklite_test.cc, tests/cli_test.cc, tests/restorableappengine_test.cc
The goal of the change is to address a need for connection with Registry during app startup.
To achieve this, the following steps are taken:
- Images are loaded into the Docker store immediately after being pulled onto a device (into the Skopeo's image store).
- `docker compose pull` is invoked after the images have been loaded, it updates Docker engine's DB with digest references to the images.
As result, the subsequent call `docker compose up -d` does NOT require a connection with Registry, and apps can be started when a device is offline.
=> appengine: Don't require connectivity when starting app

apps/aklite-offline/cmds.cpp, apps/aklite-offline/cmds.h
This allow a specific target in a offline installation source dir to be selected for installation. The one with a higher version is still selected by default if the parameter is omitted.
=> offline: Add --target parameter to aklite-offline install

src/composeappmanager.cc, src/docker/restorableappengine.cc, src/helpers.cc
Explicitly include boost/range/iterator_range_core.hpp when required, instead of relying on indirect header inclusion.
---
Reported and tested by @quaresmajose
=> Fix compilation with boost 1.84.0

include/aktualizr-lite/api.h, include/aktualizr-lite/cli/cli.h, src/api.cc, src/cli/cli.cc, src/liteclient.cc, src/liteclient.h, tests/aklite_offline_test.cc, tests/apiclient_test.cc, tests/fixtures/dockerdaemon.cc, tests/fixtures/liteclient/tufrepomock.cc
Verify a bundle metadata before updating a local/device TUF repo:
- check its signatures;
- check a bundle type (ci, prod), and whether it matches the device's one;
- check a bundle tag, and whether it matches the device's one;
- check whether the bundle targets are listed in the TUF targets of the device TUF repo.
Update and extend the unit tests to support the new use-cases.
=> Offline update: checking bundle metadata

docker/Dockerfile, tests/docker-daemon_fake.py
- Update golang version for `composectl` as well as its dependencies, including docker/moby and containerd in the dev/test container.
- Adjust the docker daemon mock to the golang/composectl version update.
=> docker: Update golang version of composectl utility

docker/Dockerfile, src/composeapp/appengine.cc, src/composeapp/appengine.h, src/docker/restorableappengine.h, tests/fixtures/dockerdaemon.cc
1. Use `composectl` to stop, uninstall, remove, and prune apps along with their docker images and containers.
2. Updated Dockerfile to switch to the corresponding `composectl` version.
3. Adjust the docker daemon mock to the changes.
=> apps: Use composectl to rm and prune apps

src/docker/restorableappengine.cc, tests/restorableappengine_test.cc
- Make sure none of app manifest blobs are pruned during the app store pruning if app is in use.
- Handle exceptions of the app image manifest processing during app store pruning.
- Re-fetch app if app image index is invalid.
=> Fix app pruning and status checking if one or more of its elements are invalid

src/api.cc, tests/aklite_offline_test.cc, tests/fixtures/liteclient/tufrepomock.cc
Make sure that the `shortlist` field is present, not `null`, and not empty string before using it - adding to the install target the apps that are in intersection of the tuf target app list and the `fetched-apps.shortlist` field.
This helps to overcome a problem if `fetched-apps.shortlist` is set to `""` by the ci-scripts if the `shortlist` field is not present in `preloaded_images` nor `app_shortlist` in `offline` sections of the factory config.
=> fixup!: Check shortilst value before using it

src/bootloader/bootloaderlite.cc, src/bootloader/bootloaderlite.h
Commit: fa9e0e5 (bootloader: add support for env variables, 2024-06-06) introduced a few code formatting errors, now corrected by running `make format`.
---
@igoropaniuk `make format` generates a few changes over your original code. I took the liberty of creating a new commit for it.
=> bootloader: fix format of recently added code

apps/aklite-offline/cmds.cpp, include/aktualizr-lite/aklite_client_ext.h, include/aktualizr-lite/api.h, include/aktualizr-lite/cli/cli.h, src/aklite_client_ext.cc, src/api.cc, src/cli/cli.cc, src/daemon.cc, src/main.cc, tests/apiclient_test.cc, tests/nospace_test.cc
@mike-sul please take a look at the overall set of changes. I will probably still improve the code, and also, it was not tested yet.
Main concerns:
- Make sure we do want to change the cli interface at that level. See how in the unit tests we now need to call `cli::CheckIn` explicitly most of the times before we call `cli::Install`;
- The `check-for-update-post` success callback is a bit of a problem. The original daemon behavior is to call it at the end of `GetTargetsToInstall` (like it was before the recent changes), and IMO we should keep that same behavior where possible. However, if we call the `CheckIn` method exclusively, `check-for-update-post` success should be called at the end of `CheckIn`, and, when calling the standalone pull or install operations, `GetTargetToInstall` should …
=> api, cli: Do not perform TUF checkin on every Pull or Install 

src/composeapp/appengine.cc
Remove app components only from the runtime part, i.e., the Docker store and Compose project in the appengine->remove() call, and leave their content in the OCI/blob store, as it may be needed during rollback or if a given app is listed in reset_apps. After an update completion, unused blobs are removed from the blob stores in the prune call, ensuring proper app removal if it is not listed in reset_apps.
=> appengine: Remove app only from runtime part

src/composeappmanager.cc
Added the ability to persist/retain all Target apps regardless of the compose_apps value by introducing the pseudo value "*" for reset_apps.
=> Retain all target apps

tests/device-gateway_fake.py, tests/fixtures/liteclient/devicegatewaymock.cc
Add a fsync operation inside the fake device gateway used for testing, and also add a delay before reading the generated events file. The delay is required because the sending of events inside aklite is not done synchronously. A ReportQueue flush is forced on LiteClient destruction, but we keep an instance active during the test procedure.
---
@mike-sul original results looked promising, but now I still get false negatives when running on Github. I'll take a better look tomorrow.
An alternative implementation would be to add some method to force the ReportQueue flush and make sure the execution only proceeds after the reply from the device gateway, but it is probably not worth it.
=> tests: Improve reliability of events verification

src/tuf/akhttpsreposource.h, src/tuf/akrepo.h, src/tuf/localreposource.h
Three internal header files added by commit baf54fa (tuf: Create a new API to encapsulate TUF operations, 2023-10-19) lacked the file guards. It did not lead to any apparent issue.
=> tuf: Add missing include guards in internal tuf headers

tests/apiclient_test.cc, tests/boot_flag_mgmt_test.cc, tests/daemon_test.cc, tests/fixtures/aklitetest.cc, tests/fixtures/liteclienthsmtest.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc, tests/nospace_test.cc
@mike-sul I'm ok with dropping the changes if you don't think it is worth to replace `LiteCLient` with `LiteClientMock` globally in the tests. But I believe it will bring some additional tests possibilities that can justify the change.
=> tests: Replace LiteCLient with LiteClientMock, and add improve CheckIn tests

src/appengine.cc
It turned out that g++ v14.1.1 requires explicit inclusion of the `algorithm` header to use `std::find`.
=> appengine: Add required header to use std::find

src/main.cc
Remove the "repo-server", "ostree-server", and "primary-ecu-hardware-id" command line options. Those options should be set using the config file, and adding them to command line interface options just add unnecessary complexity.
=> main: Remove redundant command line options

docker/Dockerfile
This PR restores back the functionality that utilizes `composectl` to check app running status (`composectl ps <uri>`) as well as obtaining status of all currently running apps `composectl ps`.
The functionality was reverted because of the issue in the `composectl`. Since the `composectl` issue has been fixed it makes sense to restore the reverted commits. See the corresponding PR for more details https://github.com/foundriesio/composeapp/pull/24.
=> Fix running app status check

src/composeapp/appengine.cc, src/composeapp/appengine.h, src/docker/restorableappengine.h, src/liteclient.cc, tests/aklite_offline_test.cc, tests/docker-daemon_fake.py
This reverts commit 37c0249d94ae1d399e170549acdb33bb5194a704.
The given functionality does not work if images hosted in docker.io are specified in a docker compose project file in a full format. For example, "docker.io/library/nginx:stable-alpine" or "docker.io/homeassistant/home-assistant:stable".
The dockerd removes the "docker.io" or "docker.io/library" prefix when stores such images in its store and as result returns the image URIs in the shorten format in a response to "http://localhost/images/json?all=1" request. For example, "nginx@sha256:<hash>" or "homeassistant/home-assistant@sha256:<hash>".
Therefore, it is not possible to map images listed in the compose project to images reported by dockerd unless the dockerd's URI shortening rules are taken in the "isAppInstalled" logic.
=> Revert `composectl` usage for checking whether app is installed

include/aktualizr-lite/cli/cli.h, src/cli/cli.cc, src/main.cc
Implementation was straightforward, so I just made a first version while we get seek for some feedback
=> cli: Add json output mode for 'check' and 'list' commands

src/main.cc
Adjusted some of the text in help. This is what it looks like now:
```
aktualizr-lite command line options:
-h [ --help ]         Print usage
-v [ --version ]      Prints current aktualizr-lite version
-c [ --config ] arg   Configuration file or directory path
--loglevel arg        Set log level 0-5 (trace, debug, info, warning, error, 
fatal)
--update-name arg     Name or version of the target to be used in pull, 
install, and update commands. default=latest
--install-mode arg    Optional install mode. Supported modes: 
[delay-app-install]. By default both ostree and apps 
are installed before reboot
--interval arg        Override uptane.polling_secs interval to poll for 
updates when in daemon mode
--json arg            Output targets information as json when running check 
and list …
```
=> Adjust help strings for options 

src/api.cc
Add some local changes in order to better organize the api.cc code. Key objective is to simplify CheckIn* methods, moving code to separate methods when appropriate, and also reducing code duplication. There is still work to be done in that direction, but the current set of changes already represent an improvement.
---
@mike-sul I still need to give it some additional testing, but it should be ready for review.
=> Improve API code organization

src/aklite_client_ext.cc, src/cli/cli.cc, src/composeappmanager.cc, src/composeappmanager.h, src/liteclient.cc, src/liteclient.h
This is what the DonwloadStarted event details look like for an "apps sync" update operation:
```
Syncing Active Target Apps
- shellhttpd2: missing installation, to be re-installed
```
*(updated the above example after the latest force push)*
I've started by only adding the app name, but decided to go a little further by adding the specific reason as well, so I created a new patch on top of the original implementation.
=> Report which apps require update in DownloadStarted event

.github/workflows/ci.yml, Makefile, README.md, dev-flow.mk, dev-shell-e2e-test.sh, docker-e2e-test/.env.dev, docker-e2e-test/Dockerfile, docker-e2e-test/config.json, docker-e2e-test/docker-compose.yml, docker-e2e-test/docker-credential-fio-helper, docker-e2e-test/entrypoint.sh, e2e-test.py, pyproject.toml
Preliminar PR to facilitate discussion.
@mike-sul you can run the tests using:
```
export FACTORY=detsch-aklite-test
export USER_TOKEN=<your_fio_token>
./dev-shell-e2e-test.sh python -m pytest e2e-test.py -v
```
On the first run, the device will be registered automatically.
There are some easy improvements to be done in the test script, but my next step is to try and run it as a github action.
My idea is to increase the tests combinations, perhaps having a "fast" mode that runs in github, with no more than 50 update operations, and a slower mode that goes through some unusual update sequences and variations on the apps configuration, increasing the chances to hit some new unexpected situation.
The targets in the factory where created almost automatically, but copying some applications I …
=> e2e-tests: Add end-to-end test script and docker compose app

src/composeappmanager.cc
Stop apps being updated only if ostree update and reboot is expected. Stopping apps in the case of an "app-only" update is not optimal, as it stops all app services/containers. In contrast, `docker compose up` can handle this more efficiently by restarting only those service containers whose images have been updated.
=> composeappmanager: Stop apps only if rootfs update is expected

Makefile
The additional aktualizr-lite check command added in commit b628f99 (makefile: Add check operation on make update) introduced an issue where the `make update` command stops before trying the aktualizr-lite pull and install commands when there is an update to be performed, since in that case, the check command returns an exit code != 0.
This commit ignores the return code of the check command, allowing the `make update` command to always proceed to pull + install.
=> makefile: Fix make update command

src/docker/restorableappengine.cc
Print logs about an app start and successful completion.
Logs printed to stdout by processes/utilities spawned by aklite are supressed since some of the utilities do odd/crazy stuff in the std output which makes aklite logs messy. As drawback, it makes successful execution some of utilities invisible, in particular `docker compose up` which is an important to see in the logs. This change prints logs before starting an app and just after successfull execution, so it becomes visible when an app was started. Note: if an app start failure occurs, then aklite will add the stderr output of the command to the aklite's logs.
=> restorableappengine: Log app start

src/composeappmanager.cc, src/composeappmanager.h, src/docker/restorableappengine.cc
Make sure that the check whether app is fetched is performed only once
during a single update cycle.
- If app is not running then don't check if it is fetched since it going
to be re-updated anyway which implies checking for missing app blobs
and pulling them if any.
- If app is enabled for running and is running then whether it is fetched
or not is done before checking the "reset" apps fetch, so the later is skipped.
=> Optimize app fetch check

src/composeapp/appengine.cc, src/composeapp/appengine.h
If an app is successfully fetched and checked then mark it as "fetched" so the next time the app fetch check is called no need to invoke the full blown check performed by `composectl`.
=> appengine: Optimize app fetch check

src/liteclient.cc, src/liteclient.h, src/main.cc
Only prune on startup, or when an installation is being finalized.
=> apps: Avoid pruning unused apps on every check operation

src/exec.h
@mike-sul not strictly required, but I think it can be useful to have this merged in `v94`  to easily verify the effectiveness of the recent changes, and also debug any other performance issues we may still have related to calling external commands while managing apps in v94.
=> apps: Log execution of external commands during apps management

docker/Dockerfile, src/composeapp/appengine.cc, src/composeappmanager.cc
Check whether an app is installed while verifying whether an app is running or not in `appengine.isRunning()` call. It guarantees that the running app is exactly what is expected to be running.
=> Check app installation along with app running

src/composeappmanager.cc, src/composeappmanager.h
Introduce a new configuration var, `[pacman].stop_apps_before_update`, to control whether apps should be forcibly stopped just before their update during an "app-only" update (when no OSTree update is involved).
By default, this variable is set to true, meaning apps are stopped before their update even if no OSTree update occurs.
If there is OSTree update too, then apps are stopped unconditionally; the new conf var is ignored.
=> composeappmanager: Make app stopping configurable

docker/Dockerfile
Relevant changes:
- 97ea634 check: Make app install status public
- 333acad root: Add function to expose composectl config
- 91443c5 test: Prune app images when uninstalling app
- 1c89b6b uninstall: Add flag to optionally prune images
- 5e8d9ed test: Make app publishing self-contained
- 8e897c2 test: Remove image just after upload to registry
- 593cad5 test: Remove bash usage in shell script
- 363ff36 check: Unify app installation check
- c45d8ea ps: Mark app as present in store if its tree is loaded
- 71c8316 check:  Add a quick way to check if app is fetched
- 220e51c ps: Check bundle integrity of running app
- cf7c427 install: Check installed app bundle integrity
- 5c7da30 app: Attach app index node to app tree if present
- 720031e publish: Limit size of app bundle
- 5bb0f02 publish: …
=> docker: Bump composectl to ab20bf9

src/main.cc
If the latest target (target with the highest version) listed in the updated TUF targets metadata has lower version than the currently installed and running target, then skip updating to such the latest version found in the TUF metadata.
=> main: Forbid target downgrade

apps/aklite-offline/cmds.h, apps/aklite-offline/main.cpp
Adds a description to each subcommand, and use a format similar to fioctl help.
---
Cherry-picking 88fff0aa692504cca8617a0d5c882957e2cfcc03 to `v95`
=> offline: Improve usage help text

src/aklite_client_ext.cc
This fix complements ba7d665 (api: Fix rollback to target that is not in TUF metadata) for the case when a rollback is initiated during the install operation.
---
We need to add this to `v95` as well.
=> api: extended: Fix rollback to unlisted target

src/daemon.cc
Commit ba7d665 (api: Fix rollback to target that is not in TUF metadata) added additional parameters PullAndInstall call within the daemon, but there was one (optional) parameter missing, leading to incorrectly setting `do_install` based on `GetTargetToInstall` result instead of `require_target_in_tuf`.
This commit adds the missing `do_install=true` parameter.
=> daemon: Fix setting of parameters for target installation

src/api.cc, src/composeappmanager.cc, tests/apiclient_test.cc
- Store a list of required apps in context of the target being installed.
- Avoid starting of the app that was not fetched before reboot while running the update finalization after reboot. It can happen if the `compose_apps` list value changes in the ostree-based rootfs during the given target.
- The following "sync" update fetches, installs, and starts the newly enabled.
=> api: Don't start newly enabled apps during finalization

docker-e2e-test/e2e-test.py
Some additions to the e2e-test script, including tests for:
- Tags switching
- Automatic downgrade prevention
- `delay-app-install` mode (which detects the issue fixed in #409)
The PR also contains general code improvements, that made it easier to expand the tests.
=> Improve end-to-end tests

src/composeappmanager.cc
Force all enabled app installation if the `force_update` is set to `"1"`. Consequently, it leads to apps stopping before installation even if they are not changed/updated.
=> composeappmanager: Force app installation if enabled

docker-e2e-test/entrypoint.sh
There were a few double quotation marks missing.
=> e2e-tests: Fix format of yaml files generated by entrypoint.sh

src/aklite_client_ext.cc, src/api.cc, src/composeapp/appengine.cc, src/composeappmanager.cc, src/docker/composeappengine.cc, src/docker/dockerclient.cc, src/docker/restorableappengine.cc, src/exec.h, src/liteclient.cc, tests/aklite_offline_test.cc, tests/aklite_rollback_ext_test.cc, tests/aklite_rollback_test.cc, tests/aklite_test.cc, tests/apiclient_test.cc, tests/boot_flag_mgmt_test.cc, tests/cli_test.cc, tests/composeapp_test.cc, tests/composeappengine_test.cc, tests/daemon_test.cc, tests/docker_test.cc, tests/exec_test.cc, tests/fixtures/composeapp.cc, tests/fixtures/dockerdaemon.cc, tests/fixtures/dockerregistry.cc, tests/fixtures/liteclient/devicegatewaymock.cc, tests/fixtures/liteclienttest.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc, tests/nospace_test.cc, tests/restorableappengine_test.cc
Keep using the deprecated v1 process API, but adjust the namespace to allow the binaries to be build with Boost 1.88.0.
It is possible to reduce the reliance on the deprecated API, I did code changes in that direction, but I believe we can merge this PR first, and then gradually get other improvements integrated as we find appropriate.
=> Support for Boost >= 1.88.0

src/composeapp/appengine.cc, src/docker/composeappengine.cc, src/docker/restorableappengine.cc, src/exec.h, src/liteclient.cc, tests/exec_test.cc
Not sure we want to add those changes for now, as PR #421 already address the more urgent situation of building against Boost 1.88.0.
As stated in https://github.com/foundriesio/aktualizr-lite/commit/0983295d30b4e526ae725c9495f4f45be994d377 message, there are a few simplifications that were done.
=> Avoid deprecated boost process API

docker-e2e-test/Dockerfile
@mike-sul The recent merge in composeapp broke the build in our test env, due to the update in  golang required version. We can update the golang version in the Dockerfile as well, but I think we can pin the composeapp first, and then decide how to manage the golang version / composeapp version properly later.
=> e2e-tests: Pin composeapp version to v95.1

.github/workflows/ci.yml, dev-shell, docker-e2e-test/Dockerfile, src/composeappmanager.cc
- App service health must be equal to "healthy" to consider it healthy, not just != "unhealthy" because the health value set by docker can be equal to "starting" or "none" which indicates that a service is not healthy.
- If the health is not specified then deduce service health based on its state.
- If a service health is not set in app status returned by the app engine then deduce it based on a service state and set it in the service status json.
=> composeappmanager: Fix app health deducing
