.jobserv.yml
The PRs will fail for now, but this should get us going and motivated.
=> Add .jobserv.yml to get PR testing

src/helpers.cc, src/helpers.h
- switch to 2020.6+fio
- adjust implementation to changes in ImageRepository interface
=> aktualizr: switch to 2020.6+fio

src/main.cc
=> Don't reboot a device if non-daemon mode

src/helpers.cc, src/helpers.h, src/main.cc, tests/test_lite.sh
=> Fix and improve Target matching

src/composeapp.cc, tests/composeapp_test.cc
=> Pull container images sequentially

src/helpers.cc, src/helpers.h, src/main.cc, tests/helpers_test.cc, tests/test_lite.sh
- Log Active Target (short version) at the beginning of each check/update loop
- Log Active Target and New Target diff if they mismatch
- Log Active and New Targets details just before updating to New one
=> Improve log messages

src/helpers.cc, src/helpers.h, src/main.cc
=> Report aktualizr config to server

src/main.cc
This has always given rather random output. This sorts by the version
number using a flat_map.
=> Fix sorting of the "list" subcommand

src/helpers.cc, tests/helpers_test.cc
=> docker-apps: Turn off the docker app pack manager

src/composeappmanager.cc
=> fixup: Remove apps from the list safely

src/main.cc
=> Output aklite version if '-v' is specified

src/main.cc
Make sure that Apps to be updated are checked just after aklite restart
if there is a new Target. It does not suffice to verify the app list
in the config and whether currently installed Target's Apps are actually installed
and running. A new check has to happen if a new Target is discovered.
=> fixup! Update Apps if a new Target after restart

src/composeappmanager.cc
LiteClient expects error code/boolean as a return code and use it to
determine Target download and install status. We need to adjust the
ostree apps implementation to the given protocol.
=> ostree-apps: catch pull and checkout exceptions

src/composeappmanager.cc, src/composeappmanager.h, src/helpers.cc, src/helpers.h, src/main.cc
This gives us the ability to attach a little more context as to why we start an update as well as how the update completed.
=> Add details for why an install was started and how it completed

src/liteclient.cc
=> fixup!: add x-ats-target header at http client instantiation

dev-shell, docker/Dockerfile
=> dockerfile: install libfyaml

src/compose/composeappmanager.cc, src/liteclient.cc, src/liteclient.h, src/main.cc, tests/test_lite.sh
don't finalize a pending installation if `list` or `status` command is called.
=> Don't finalize if status or list command

docker/Dockerfile
=> docker: build libfyaml within a single layer

README.md, how-to-run-locally.md
=> doc: add info about enabling of HSM support

src/composeappmanager.cc
as discussed, implement the bootloader functionality in aktualizr-lite
=> Bootloader

src/appengine.h, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.cc, src/docker/composeappengine.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, tests/composeapp_test.cc, tests/composeappengine_test.cc, tests/liteclientHSM_test.cc, tests/liteclient_test.cc
1:1 replacement of the containerDetails request.
=> composeappmanager: replace docker ps with REST api

src/bootloader/rollbacks/rollback.h
=> bootloader: fix rollback

src/docker/composeappengine.cc, src/docker/dockerclient.cc, src/docker/dockerclient.h
* Make a request to dockerd once per App;
* Add more info about running Apps into the event report.
=> Improve App status reporting

src/liteclient.cc, src/liteclient.h, src/main.cc, tests/fixtures/liteclienthsmtest.cc, tests/fixtures/liteclienttest.cc
Make sure that just one instance of 'aklite daemon' or 'aklite update' is running simultaneously.
=> Aklite lock

src/liteclient.h
=> aklite: remove leftovers of the former update lock

src/liteclient.cc, tests/test_lite.sh
=> client: Include pacman tag(s) in current-target file

src/liteclient.cc
=> aklite: update `current-target` file before callback

src/docker/docker.h, src/docker/dockerclient.cc, src/docker/dockerclient.h, src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/aklite_test.cc, tests/fixtures/composeapp.cc, tests/fixtures/dockerdaemon.cc, tests/fixtures/dockerregistry.cc, tests/restorableappengine_test.cc
- Download a layer manifest if present.
- Get a list of new App's layers that are missing in a local store.
- Check if there is sufficient amount of available storage to accommodate the missing layers of a new App.
- Add tests to cover the use-case happy path as well as edge cases.
=> Check App size before update

src/docker/restorableappengine.cc, src/docker/restorableappengine.h, tests/restorableappengine_test.cc
- Traverse through each element of App's Merkle tree in order to verify whether it's completely fetched or not.
- Tests to verify the procedure that checks whether App is entirely fetched.
=> Complete check whether App is fetched

src/docker/dockerclient.cc
=> apps: docker: remove curl usage

apps/aklite-apps/cmds.cpp, apps/aklite-apps/cmds.h, apps/aklite-apps/main.cpp
=> aklite-apps: Rename `hack` command to `register`

src/offline/client.cc
Adjust the offline client config to make sure it works if the default
configuration values are set, i.e. when a user doesn't specify them at all.
=> aklite-offline: Adjust default configuration

include/aktualizr-lite/api.h, src/api.cc, src/composeappmanager.cc, src/composeappmanager.h, src/docker/composeappengine.cc, src/docker/dockerclient.cc, src/docker/dockerclient.h, src/docker/restorableappengine.cc, src/liteclient.cc, src/liteclient.h, src/main.cc, tests/composeappengine_test.cc, tests/restorableappengine_test.cc
=> apps: Obtain and send info about running Apps

src/offline/client.cc, tests/aklite_offline_test.cc
Support offline update if the update content doesn't include any Apps.
=> aklite-offline: Fix to support ostree-only update

tests/fixtures/liteclienthsmtest.cc
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>
=> aktualizr: require pkcs11 token label

src/offline/client.cc, tests/aklite_offline_test.cc
1. A fix of the offline update if one or more of Target apps are missing in the source content.
2. A test that verifies the offline update in such the case.
=> Fix offline update if one or more of Target apps are missing

include/aktualizr-lite/api.h, src/api.cc
=> api: Add method to obtain device's UUID

src/docker/restorableappengine.cc
Extract just compose file from the App archive in order to check a
compose project configuration during the "verification" step of
an overall update cycle.
=> Extract only a compose file to verify App

src/docker/composeappengine.cc, src/docker/restorableappengine.cc
Multiply an app archive size by 3 instead of 10 to estimate an app bundle size.
=> apps: Be more optimistic while estimating App size

src/offline/client.cc
istream::readsome() is not quite good way to read data from an input stream as it reads "immediately available" characters from an input stream. The "immediately available" is implementation and platform specific, so its behavior is not consistent across all platforms. Also, as the doc states it
"may always return zero and extract no characters".
=> offline-client: Fix app blob download

CMakeLists.txt, examples/custom-client-cxx/main.cc, include/aktualizr-lite/api.h, src/CMakeLists.txt, src/api.cc, src/cli/cli.cc, src/cli/cli.h, src/liteclient.cc, src/liteclient.h, src/main.cc, src/target.cc, src/target.h, tests/CMakeLists.txt, tests/cli_test.cc, tests/test_lite.sh
Dogfooding the API by implementing the update/finalize CLI commands.
Also, it has helped slightly improve the API.
=> Api based cli update cmd

src/cli/cli.cc
Add meaningful logs for the rollback cases.
=> cli: Add logs for the rollback after boot cases

Makefile, dev-flow.mk, docker/Dockerfile, src/ostree/repo.cc, tests/composeapp_test.cc, tests/device-gateway_fake.py, tests/fixtures/liteclient/rootcapki.cc, tests/fixtures/liteclient/serverpki.cc
=> Move to openssl v3

examples/custom-client-cxx/main.cc, include/aktualizr-lite/api.h, src/api.cc, src/cli/cli.cc, src/liteclient.cc, src/liteclient.h, src/main.cc, tests/apiclient_test.cc, tests/fixtures/liteclienttest.cc
Fix a few subtle issues discovered during another e2e test session.
=> Fix CLI implementation

src/composeappmanager.cc
It makes sense to stop the apps that are about to be updated just before the ostree installation. If a device unexpectedly turns off immediately after a successful ostree installation but before the apps are updated, then this change ensures that the apps of the previous version are not automatically started upon boot.
=> composeappmanager: Stop Apps just before updating

CMakeLists.txt, src/docker/restorableappengine.cc, src/main.cc, tests/CMakeLists.txt, tests/apiclient_test.cc, tests/fixtures/fstatvfs-mock.cc, tests/fixtures/liteclient/ostreerepomock.cc, tests/fixtures/liteclient/tufrepomock.cc, tests/fixtures/liteclienttest.cc, tests/liteclient_test.cc, tests/nospace_test.cc, tests/ostree_test.cc
This is an improvement/cleanup and an extension of the static delta-related test.
This change is a prerequisite for the follow-up change related to the application of delta stats/size.
=> Improvements and cleanup related to the static delta use-case.

src/bootloader/bootloaderlite.cc, src/ostree/sysroot.cc, src/ostree/sysroot.h, src/rootfstreemanager.cc
- Fix the delta-based update issue discovered during e2e testing.
- Properly handle errors/exceptions that may happen during checking if there is enough storage to accommodate an update.
=> Delta stat usage fixes

src/rootfstreemanager.cc, tests/nospace_test.cc
- Don't pull ostree if the amount of free storage is lesser than the amount of reserved storage (no delta case).
=> Don't pull ostree if no available storage

src/docker/composeappengine.cc
It might happen that the compose app state file is missing when a call to run it is invoked. This should not happen under normal circumstances since the previous `fetch` call makes sure the state file is created and set.
However, in the case of switching from the restorable app type to compose one or manual app pull (`docker-compose pull/up` the app's compose dir ends up with no state file at the moment of its running. So, this fix assumed that the app is pulled if `run` is called and enforces the app state file setting to the `pulled` state. Even if the app compose content is missing the run command will pull it.
=> apps: Assume stateless app is pulled when running it

apps/aklite-offline/cmds.cpp, apps/aklite-offline/cmds.h, apps/aklite-offline/main.cpp, src/offline/client.cc, src/offline/client.h, src/ostree/repo.cc, src/ostree/repo.h, src/target.cc, src/target.h, tests/aklite_offline_test.cc, tests/ostree_test.cc
Inspect the specified source directory for offline update and print detected Target details.
The output looks like the following:
```
info: Reading config: "<path>/sota.toml"
Found Targets: 
Name: intel-corei7-64-lmp-2177
OSTree hash: 5e1d2005f95b0f6ad811236420f4646d2fe967101aaf275cc598b9e4f32e89cb
Apps:
app-04 -> hub.foundries.io/msul-dev01/app-04@sha256:c5a6dea1f4f19d76706b04b2b5fc61783be5d2d60c029aeaff92759f91045a0a
Name: intel-corei7-64-lmp-2174
OSTree hash: 8ee84990194625102dd17e520021549dd8dbcc21a398b47c3f00feefea570793
Apps:
app-04 -> hub.foundries.io/msul-dev01/app-04@sha256:c5a6dea1f4f19d76706b04b2b5fc61783be5d2d60c029aeaff92759f91045a0a
Name: intel-corei7-64-lmp-2170
OSTree hash: 0b30e5af6e9b227eb72a029555183f0b2b729c9af24a25ed8158accb1ec43920
Apps:
app-04 -> …
```
=> Check the offline udpate source directory

tests/docker-daemon_fake.py
The offline test suite uses a real `composectl` utility which streams the image load manifest to a docker daemon. Therefore, the docker daemon mock should support receiving the manifest transferred via a chunked HTTP stream, otherwise the offline unit tests fail.
=> tests: Support chunked streaming of image load manifest

src/main.cc
The aktualizr-lite executable was using a different locking mechanism if compared to the one used in the aklite API, allowing concurrent execution between the two methods. This commit changes the aktualizr-lite executable so that it uses the mechanism originally used in the API, which relies on flock(LOCK_EX).
=> main: Unify locking mechanism, using the same mechanism as the API

apps/tufctl/main.cpp, include/aktualizr-lite/tuf/tuf.h, src/api.cc, src/tuf/akhttpsreposource.cc, src/tuf/akhttpsreposource.h, src/tuf/akrepo.cc, src/tuf/akrepo.h, src/tuf/localreposource.cc, src/tuf/localreposource.h
Also add an implementation to AkRepo class.
---
@mike-sul not sure if that is what you need.
=> tuf: Add GetRoot method to TUF API

src/offline/client.cc
Use device's TUF metadata if the TUF meta provided in the offline update bundle is older than the device's one.
=> offline: Use device TUF meta if bundle one is outdated

docker/Dockerfile, src/composeapp/appengine.cc, src/composeapp/appengine.h, src/composeappmanager.cc, src/docker/restorableappengine.h, src/liteclient.cc, tests/aklite_offline_test.cc, tests/docker-compose_fake.py, tests/docker-daemon_fake.py
Use composectl to check app state:
1. whether app is fetched,
2. whether app is installed,
3. whether app is running.
Adjust unit tests to removing C++ code to check app state and using `composectl` instead.
=> Use composectl to check app state

include/aktualizr-lite/cli/cli.h, src/cli/cli.cc
Single commit PR, on top of PR #345
=> cli: Add function returning string description of StatusCode values 

README.md
@mike-sul I'm basically linking existing documentation. I could add more content to the README.md file itself, based on the linked documentation, if you think it is worth spending the time doing that.
=> readme: Add section guiding testing on devices

include/aktualizr-lite/aklite_client_ext.h, include/aktualizr-lite/api.h, src/aklite_client_ext.cc, src/api.cc, src/cli/cli.cc, src/daemon.cc
=> Fix rollback and apps sync update when target is not listed in TUF anymore

.github/workflows/ci.yml
Restore the end-to-end test workflow action back.
=> Revert "ci: remove the e2e test workflow"

apps/aklite-offline/cmds.h, apps/aklite-offline/main.cpp
Adds a description to each subcommand, and use a format similar to fioctl help.
---
@vanmaegima suggestions about the newly added description text for each subcommand are welcome (look for `Cmd("` in the changes bellow)
=> offline: Improve usage help text

src/main.cc
Add a description to every subcommand, and improve the help output format.
----
Doing a similar improvement to that I've done in aklite-offline (PR #390).
=> main: Improve help message

docker-e2e-test/e2e-test.py, include/aktualizr-lite/aklite_client_ext.h, include/aktualizr-lite/api.h, include/aktualizr-lite/cli/cli.h, src/aklite_client_ext.cc, src/api.cc, src/cli/cli.cc, src/liteclient.cc, src/liteclient.h, src/main.cc
This reverts commit c658acb56c2f1028a979ac6c36778cb822bf1b36, reversing changes made to 938cab5e63a270df0d25df83573ee0d3a3c4545a.
=> Revert "Merge pull request #381 from foundriesio/detsch-user-rollback"

src/exec.h
Tiny adjustments to support boost 1.87.0
=> Make boost 1.87.0 happy

include/aktualizr-lite/api.h, src/aklite_client_ext.cc, src/api.cc, src/cli/cli.cc, src/liteclient.cc, src/liteclient.h
Once approved, I'll proceed to backport the changes to `v94`.
=> Fix apps-only rollback triggered during finalization

src/composeappmanager.cc
- App service health must be equal to "healthy" to consider it healthy, not just not equal "unhealthy" because the health value set by docker can be equal to "starting" or "none" which indicates that a service is not healthy.
- If the health is not specified then deduce service health based on its state and set it in the service status json. It helps to unify status sent to Device Gateway regardless of the app engine used (restorable or composectl) and their versions.
=> composeappmanager: Fix app health deducing
